### ISSUE TITLE
SPI Transaction length should be in bits

### ISSUE THREAD

**Issue by Scottapotamas** [MisterRager/ESP32_APA102#1]
The SPI transaction length as described here won't send a valid buffer of data to the LED:
https://github.com/MisterRager/ESP32_APA102/blob/7d3899d0672154b63dd41b5a0e45a74f3c4aa39d/APA102.cpp#L34

As per the ESP docs, the [length field is in bits](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/spi_master.html#_CPPv4N17spi_transaction_t6lengthE). Therefore it needs to be multiplied by 8 for the SPI peripheral to correctly clock out the full buffer.

The correct version reads like so:

```C
 transaction.length = bufferSize * 8; 
```
___

For reference, I'm using `ESP-IDF 4.2` with my own driver in C (which isn't relevant).

**Comment by MisterRager** [comment]
I've revisited the APA102 lights a few times since then but hadn't finished a project without a few bodges until this year's winter lighting array. Thanks for the heads-up on that API param. This should be fixed, now.

**Comment by MisterRager** [comment]
The convenience builder makes sure to multiply by eight:
https://github.com/MisterRager/ESP32_APA102/blob/master/src/APA102Chain.cpp#L59
